### PR TITLE
Main fix bugs

### LINKED ISSUE #9: Adding a Task
When adding a task if you have the day that you are adding to drop down, it wont appear unless you refresh it/ close the drop down and drop it back

### LINKED ISSUE #15: Bug Fixes
### Requirements 
- Bug fixing for todo list

### List of bugs
- If the dropdown for a specific day is open and we add a new task to that day, the new task doesn't appear unless we close and reopen the dropdown
  - Proposed change: add the following code to the bottom of `addTask` function: `renderTasks(day.toLowerCase());`

### PR DESCRIPTION
**Pull request by Azathotha**
fix added and removed tasks not showing immediately
update task id when loading data

### CODE REVIEW

**Review by HarshGurnani — APPROVED** [review]
LGTM

**Comment by sarveshmann** [comment]
Looks good! Thanks!

**Review by sarveshmann — APPROVED** [review]
Looks good! thanks!

**Review by geenalimfat — APPROVED** [review]
looks good :)

**Review by symsoph — APPROVED** [review]
good to merge!

**Pull request merged**
